---
- name: Deploy and Build Local Strava Dashboard with Docker Compose via Shell
  hosts: local
  become: yes

  vars:
    venv_path: "/home/schatzm/.venv_docker_compose"
    your_raspberry_pi_username: "schatzm"
    python_version: "3.9"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Ensure Python 3.9 is installed
      apt:
        name: python{{ python_version }}
        state: present

    - name: Ensure pip for Python 3.9 is installed
      apt:
        name: python{{ python_version }}-pip
        state: present

    - name: Ensure virtualenv for Python 3.9 is installed
      apt:
        name: python{{ python_version }}-venv
        state: present

    - name: Create virtual environment for Docker Compose (Python 3.9)
      command:
        cmd: "python{{ python_version }} -m venv {{ venv_path }}"
      args:
        creates: "{{ venv_path }}/bin/activate"

    - name: Upgrade pip and setuptools in virtual environment (Python 3.9)
      pip:
        name:
          - pip
          - setuptools
        virtualenv: "{{ venv_path }}"
        executable: "{{ venv_path }}/bin/pip{{ python_version }}"
        state: latest

    - name: Install PyYAML in virtual environment (Python 3.9)
      pip:
        name: PyYAML
        virtualenv: "{{ venv_path }}"
        executable: "{{ venv_path }}/bin/pip{{ python_version }}"

    - name: Install Docker Compose in virtual environment (Python 3.9)
      pip:
        name: docker-compose
        virtualenv: "{{ venv_path }}"
        executable: "{{ venv_path }}/bin/pip{{ python_version }}"

    - name: Ensure project directory exists
      file:
        path: /home/{{ your_raspberry_pi_username }}/local_strava_dashboard
        state: directory

    - name: Clone Git repository
      git:
        repo: https://github.com/martinschatz-cz/local_strava_dashboard.git
        dest: /home/{{ your_raspberry_pi_username }}/local_strava_dashboard
        update: yes

    - name: Build and start Docker Compose project
      shell:
        cmd: "{{ venv_path }}/bin/docker-compose up -d --build"
        chdir: /home/{{ your_raspberry_pi_username }}/local_strava_dashboard