---
- name: Deploy and Build Local Strava Dashboard with Docker Compose via Shell
  hosts: local
  become: yes

  vars:
    your_raspberry_pi_username: "schatzm"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install essential system packages
      apt:
        name:
          - python3
          - python3-pip
          - docker.io
        state: present

    - name: Install Docker Compose using Pip with specific PyYAML version
      ansible.builtin.pip:
        name:
          - pyyaml==5.3.1
          - docker-compose
        state: present
        executable: pip3

    - name: Ensure project directory exists
      file:
        path: /home/{{ your_raspberry_pi_username }}/local_strava_dashboard
        state: directory

    - name: Clone Git repository
      git:
        repo: https://github.com/martinschatz-cz/local_strava_dashboard.git
        dest: /home/{{ your_raspberry_pi_username }}/local_strava_dashboard
        update: yes

    - name: Build and start Docker Compose project
      shell:
        cmd: docker-compose up -d --build
        chdir: /home/{{ your_raspberry_pi_username }}/local_strava_dashboard