---
- name: Deploy Local Strava Dashboard with Docker Compose on Raspberry Pi
  hosts: local
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Ensure project directory exists
      file:
        path: /home/schatzm/local_strava_dashboard
        state: directory

    - name: Clone Git repository
      git:
        repo: https://github.com/martinschatz-cz/local_strava_dashboard.git
        dest: /home/schatzm/local_strava_dashboard
        update: yes

    - name: Build and start Docker Compose project
      shell:
        cmd: docker-compose up -d --build
        chdir: /home/schatzm/local_strava_dashboard